my_string=input("Что-то надо написать: ")
print("Длина строки:", len(my_string))
print("Верхний регистр: ", my_string.upper())
print("Нижний регистр:", my_string.lower())
print("Без пробелов:", my_string.replace(" ",""))
print("Первый символ:", my_string[0])
print("Последний символ:", my_string[-1])